x-common: &common
  restart: always
  env_file:
    - .env

x-common-volumes: &common-volumes
  volumes:
    - ./app:/app/app
    - ./alembic:/app/alembic
    - ./requirements.txt:/app/requirements.txt
    - ./.env:/app/.env
    - ./entrypoint.sh:/app/entrypoint.sh

services:

  alembic:
    build:
      context: .
      dockerfile: Dockerfile
    <<: 
      - *common
      - *common-volumes
    command: [ "alembic", "upgrade", "head" ]
    restart: "no"


  app:
    build:
      context: .
      dockerfile: Dockerfile
    <<: 
      - *common
      - *common-volumes
    ports:
      - 8669:8669
    command: [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8669", "--workers", "4", "--reload" ]
    depends_on:
 
      alembic:
        condition: service_completed_successfully